### ISSUE TITLE
migrate explains ideas to issues

### ISSUE THREAD

**Issue by asottile** [anthonywritescode/explains#1]

**Comment by int3l** [comment]
Would you like me to help with this one?
I can extract and create new issues according to the existing wiki video idea list.

**Comment by asottile** [comment]
I actually think it might make sense to keep it in the wiki page -- the page has gotten too long and it'd be much harder to sift through github issues

**Comment by int3l** [comment]
Maybe close this issue then?

PS: video idea (short) for [doctest](https://docs.python.org/3/library/doctest.html) - I see a lot of examples with this module, but it seems that not many people know about it and how to use it.

**Comment by janosh** [comment]
Where to post topic suggestions now? Assuming issues, let me suggest the [`fileinput` module](https://docs.python.org/3/library/fileinput.html).

**Comment by asottile** [comment]
as always: twitch chat, discord, twitter

`fileinput` is kinda awful and I would not recommend it

**Comment by janosh** [comment]
> as always: twitch chat, discord, twitter

Issues would be better imo. More permanent with up/down voting.

> `fileinput` is kinda awful and I would not recommend it

Yeah, I had difficulty using it and the docs weren't helping. Will steer away.
