### ISSUE TITLE
C extensions (ep134) error

### ISSUE THREAD

**Issue by fredrikaverpil** [anthonywritescode/explains#211]
Hi @asottile !

Many, many thanks for all your great YouTube videos. I've made it into a habit to check for new videos daily. 👍 

For [ep134](https://github.com/anthonywritescode/explains/tree/master/sample_code/ep134) on C extensions, I've copied your code and can run `_hello.hello_world()` just fine. But the second example, where you can pass an argument such as `_hello.hello("anthony")` does not work for me. I'm on Ubuntu 20.04 LTS with pyenv-installed Python 3.9.7 (via WSL2).

You can see what I have in [my repo](https://github.com/fredrikaverpil/python-c-extension) (some slight modifications on module/function naming, added comments), and how I can reproduce the error in [in GitHub Actions](https://github.com/fredrikaverpil/python-c-extension/runs/3685679101): 

```
Traceback (most recent call last):
  File "/home/runner/work/python-c-extension/python-c-extension/tests.py", line 6, in <module>
    ret = hello.greet("fredrik")
TypeError: hello.greet() takes no arguments (1 given)
Error: Process completed with exit code 1.
```

I was just wondering if you can spot what might be going wrong here?

**Comment by asottile** [comment]
your version: https://github.com/fredrikaverpil/python-c-extension/blob/cf3662dd2a7ebf37ac0db601f865f785ca333ed8/hello.c#L37

does not match the video: https://github.com/anthonywritescode/explains/blob/43943ea81a4e42f6b980dbd6c1c8841effa67c24/sample_code/ep134/rev05/_hello.c#L25

**Comment by fredrikaverpil** [comment]
Aaah, I used `METH_NOARGS` where it should've been `METH_VARARGS`. Many thanks!
