### ISSUE TITLE
Topic suggestion: `/` in function signature

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [anthonywritescode/explains#358]
Hi Anthony. I really appreciate and love the videos! I'm always excited when I see that you've uploaded a new one.

Today, I recently encountered the `/` in a function signature (specifically in the numpy docs). I looked it up, thought I understood it, though was confused why it exists in the first place.

Then today in your tuples video, I saw in that man page of `tuple`, a lot of the operator function signatures had `/` at the end of their signatures. That confused me since there were no arguments to follow there.

Do you think it would be worthwhile to make a video on this (and maybe the `*`) in function signatures.

Thanks!

**Comment by asottile** [comment]
!explains argument parameters
