### ISSUE TITLE
Type annotations with generic types like (Container/collections.abc and etc.)

### ISSUE THREAD

**Issue by int3l** [anthonywritescode/explains#79]
Level: intermediate?

I saw the usage of `Container` type hinting on stream, while refactoring `pyupgrade` -- thought that it will be a good topic for a video. 

- why and when it is useful to use them (explaining the concept of [Generic Alias Type](https://docs.python.org/3/library/stdtypes.html#generic-alias-type))
- different generic types
- mypy interactive examples

PS: Hi chat 😜

**Comment by asottile** [comment]
I plan to have ~2 videos on this topic already: generic vs concrete parameters for apis, and Generic in general
